name: TCM Türkiye İçerik Toplama

on:
  schedule:
    # Her gün saat 03:00 UTC'de çalıştır (Türkiye saati ile 06:00)
    - cron: '0 3 * * *'
  
  # Manuel tetikleme için
  workflow_dispatch:
    inputs:
      scraper_type:
        description: 'Çalıştırılacak scraper türü'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - research
          - theory
          - clinical
          - events

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Kodu kontrol et
      uses: actions/checkout@v3
    
    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: İçerik toplama işlemini çalıştır
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          python -m tcmturkiye.main --type ${{ github.event.inputs.scraper_type }}
        else
          python -m tcmturkiye.main --type all
        fi
    
    - name: Değişiklikleri kaydet
      run: |
        git config --global user.name "TCM Türkiye Bot"
        git config --global user.email "bot@tcmturkiye.com"
        git add output/content/*
        git diff --staged --quiet || git commit -m "İçerik güncellendi: $(date +'%Y-%m-%d %H:%M:%S')"
        git push
