name: Günlük İçerik Üretimi

on:
  schedule:
    - cron: '0 6 * * *'  # UTC 06:00 = Türkiye saatiyle 09:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları çek
      uses: actions/checkout@v3

    - name: Python ortamını kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: İçerik üretimini çalıştır
      run: python -m tcmturkiye.tcmturkiye
